"""
Common strings constants.
"""

AMBIG_CMD = "ambiguous cmd"
EMPTY_CMD = "empty cmd"
FAREWELL = "farewell"
FAREWELL_WITH_PARTY = "farewell with party name"
JUST_YESNO = "just yes or no"
JUST_YESNOABORT = "just yes no abort"
LIST_PREFIX = "list leader"
NO_SUCH_CHAR = "no such char"
OKAY = "okay"
WHAT = "what"

CMD_ABORT = "abort"
CMD_HELP = "help"
CMD_NO = "no"
CMD_QUIT = "quit"
CMD_YES = "yes"
