"""
Party creation string constants.
"""

EMPTY_PARTY = "empty party"
GREETING = "greeting"
LIST_OF_CHARS = "character list"
NAME_PROMPT = "name prompt"
NAME_IS = "name is"
NEW_NAME_IS = "new name is"
NEXT = "what next"
WELCOME_BACK = "welcome back"

CMD_ADD = "add"
CMD_CHANGE_PARTY_NAME = "change party name"
CMD_DELETE = "delete"
CMD_DONE = "done"
CMD_EDIT = "edit"
CMD_OVERVIEW = "overview"
CMD_QUICK_ADD = "quick add"
